Enable collecting perfview profile from windows agent.

diff --git a/eng/ci/templates/official/jobs/run-coldstart.yml b/eng/ci/templates/official/jobs/run-coldstart.yml
--- a/eng/ci/templates/official/jobs/run-coldstart.yml
+++ b/eng/ci/templates/official/jobs/run-coldstart.yml
@@ -25,8 +25,8 @@ jobs:
       os: windows
 
   variables:
-    functionAppOutputPath: $(Build.ArtifactStagingDirectory)/Published/${{ parameters.functionAppName }}
-    hostOutputPath: $(Build.ArtifactStagingDirectory)/Published/HostRuntime
+    functionAppOutputPath: $(Build.BinariesDirectory)/Published/${{ parameters.functionAppName }}
+    hostOutputPath: $(Build.BinariesDirectory)/Published/HostRuntime
     hostAssemblyPath: $(hostOutputPath)/Microsoft.Azure.WebJobs.Script.WebHost.dll
     logsDirectory: $(Build.ArtifactStagingDirectory)/Logs
     stdOutLogsFilePath: $(logsDirectory)/std_out_logs.txt
@@ -34,6 +34,21 @@ jobs:
     FUNCTIONS_WORKER_RUNTIME: 'dotnet-isolated'
     FUNCTIONS_WORKER_RUNTIME_VERSION: '9.0'
     AzureWebJobsScriptRoot: '$(functionAppOutputPath)'
+    perfviewPath: C:\.tools\perfview\perfview.exe 
+    traceDirectory: $(Build.ArtifactStagingDirectory)/out
+    traceFileName: PerfViewData_$(Build.BuildNumber)_${{ parameters.functionAppName }}.etl
+    traceFilePath: $(traceDirectory)/$(traceFileName)
+    traceLogPath: $(logsDirectory)/logs.log
+
+  ${{ if and(eq(parameters.os, 'Windows'), eq(parameters.instanceId, '1')) }}:
+    templateContext:
+      outputParentDirectory: $(System.DefaultWorkingDirectory)/out
+      outputs:
+        - output: pipelineArtifact
+          displayName: Publish perfview profile
+          path: $(traceFilePath).zip
+          artifact: PerfViewData_${{ parameters.functionAppName }}
+          condition: eq(variables['CollectPerfviewProfile'], 'true')
 
   steps:
   - template: /eng/ci/templates/install-dotnet.yml@self
@@ -76,7 +91,9 @@ jobs:
   - ${{ if eq(parameters.os, 'Windows') }}:
     - pwsh: |
         $errorLogFilePath = "$(Build.ArtifactStagingDirectory)/Logs/std_err_logs.txt"
-        Start-Process -FilePath "powershell.exe" -ArgumentList "-Command", "dotnet $(hostAssemblyPath)" -RedirectStandardOutput $(stdOutLogsFilePath) -RedirectStandardError $(stdErrorLogsFilePath) -PassThru
+        $process = Start-Process -FilePath "$(hostOutputPath)/Microsoft.Azure.WebJobs.Script.WebHost.exe" -RedirectStandardOutput $(stdOutLogsFilePath) -RedirectStandardError $(stdErrorLogsFilePath) -PassThru
+        Write-Host "Started process ID: $($process.Id)"
+        echo $process.Id > $(Build.ArtifactStagingDirectory)/hostProcessId.txt
       displayName: Start host in placeholder mode
   - ${{ else }}:
     - script: |
@@ -85,6 +102,7 @@ jobs:
         # https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#environment-variables
         export AzureWebJobsScriptRoot="$(functionAppOutputPath)"
         nohup dotnet $(hostAssemblyPath) > $(stdOutLogsFilePath) 2> $(stdErrorLogsFilePath) &
+        echo $! > $(Build.ArtifactStagingDirectory)/hostProcessId.txt
       displayName: Start host in placeholder mode
 
   - pwsh: |     
@@ -105,6 +123,20 @@ jobs:
 
     displayName: Wait until host is warmed up
 
+  - ${{ if and(eq(parameters.os, 'Windows'), eq(parameters.instanceId, '1')) }}: # collect profile only on the first instance
+    - pwsh: |
+        New-Item -ItemType Directory -Path $(traceDirectory)
+        if (Test-Path $(perfviewPath)) {
+            $collectArguments = ${env:PerfviewCollectArguments}
+            Write-Host "perfview.exe found. Executing with arguments '$collectArguments'"
+            Start-Process -FilePath $(perfviewPath) -ArgumentList "collect $collectArguments /LogFile:$(traceLogPath) /DataFile:$(traceFilePath)" -NoNewWindow
+        } else {
+            Write-Host "perfview.exe not found in $(perfviewPath)"
+            exit 1
+        }
+      displayName: Start Perfview
+      condition: eq(variables['CollectPerfviewProfile'], 'true')
+
   - pwsh: |
       $helloUrl = "http://localhost:5000/api/hello?forcespecialization=1"
       Write-Host "Calling $helloUrl"
@@ -118,6 +150,64 @@ jobs:
       Write-Host "##vso[task.setvariable variable=coldStartLatency;isOutput=true]$($duration.TotalMilliseconds)"
     displayName: Record cold start latency
     name: Record
+
+  - ${{ if and(eq(parameters.os, 'Windows'), eq(parameters.instanceId, '1')) }}:
+    - pwsh: |
+        Write-Host "Stopping Perfview..."
+        & $(perfviewPath) stop
+
+        # Wait for the zip file to be created
+        $maxAttempts = 10
+        $attempt = 0
+
+        while ($attempt -lt $maxAttempts) {
+            $files = Get-ChildItem -Path $(traceDirectory)
+            $fileCount = $files.Count
+            if ($fileCount -eq 1 -and $files[0].Name -eq '$(traceFileName).zip') {
+                break
+            } else {
+                Write-Host "Expected zip file not found. Rechecking again in 15 seconds..."
+                Start-Sleep -Seconds 15
+                $attempt++
+            }
+        }
+
+        $perfviewProcess = Get-Process -Name "perfview" -ErrorAction SilentlyContinue
+        if ($perfviewProcess) {
+            Write-Host "Killing Perfview process..."
+            $perfviewProcess | Stop-Process -Force
+        }
+
+        Write-Host "PerfView logs:"
+        Get-Content $(traceLogPath)
+      displayName: Stop PerfView
+      condition: eq(variables['CollectPerfviewProfile'], 'true')
+
+  - ${{ if eq(parameters.os, 'Windows') }}:
+    - pwsh: |
+        $processIdFile = "$(Build.ArtifactStagingDirectory)/hostProcessId.txt"
+        if (Test-Path $processIdFile) {
+            $processId = Get-Content $processIdFile
+            Write-Host "Sending SIGTERM to process ID: $processId"
+            Stop-Process -Id $processId -Force
+        } else {
+            Write-Host "Process ID file not found."
+        }
+      displayName: Stop host process
+      condition: always()
+
+  - ${{ if eq(parameters.os, 'Linux') }}:
+    - script: |
+        processIdFile="$(Build.ArtifactStagingDirectory)/hostProcessId.txt"
+        if [ -f "$processIdFile" ]; then
+            processId=$(cat $processIdFile)
+            echo "Sending SIGTERM to process ID: $processId"
+            kill -SIGTERM $processId
+        else
+            echo "Process ID file not found."
+        fi
+      displayName: Stop host process
+      condition: always()
 
   - pwsh: |
       Write-Host "Logs:"
